name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.0'
      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist
      - name: PHP Lint
        run: |
          php -l smmcare.php
          php -l includes/class-smmcare.php
